version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/devops-practical
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
